### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by ryantxu** [mejackreed/leaflet-solr-heatmap#1]
Hi Jack-

This looks great!  Can you specify a license for the project?  I am looking to build up a leaflet library for solr heatmap support and want to know if this is an appropriate place to start :)

I took a crack at showing both maps at once and doing the query externally:
https://github.com/ryantxu/leaflet-solr-heatmap/tree/more-libish

ryan

**Comment by mejackreed** [comment]
Hey @ryantxu ... thanks for prompting me on this. MIT license added bc5e9a505a9299f72c285945b12e0f00f2dc0749
